FROM registry.ci.openshift.org/stolostron/builder:go1.20-linux AS builder

WORKDIR /workspace

COPY . .

RUN  make thanos-receive-controller

FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

COPY --from=builder /workspace/thanos-receive-controller /usr/bin/thanos-receive-controller

RUN microdnf update -y && microdnf clean all

USER 65534

ENTRYPOINT ["/usr/bin/thanos-receive-controller"]
